services:
  - type: web
    name: crystaltriage
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    regions:
      - ohio
    scaling:
      minInstances: 1
      maxInstances: 3
    healthCheckPath: /
    # Don't use Docker, use native Node.js environment
