services:
  - type: web
    name: crystaltriage
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    autoDeploy: true
    regions:
      - ohio
    scaling:
      minInstances: 1
      maxInstances: 3
    healthCheckPath: /
    disk:
      name: crystaltriage-data
      mountPath: /uploads
      sizeGB: 1
